extends RefCounted
class_name EndingsData

## Character-specific endings for the world champion credits scroll.
## Empty strings = beat pauses (visual spacing).

static func get_ending(character: DartData.Character) -> Array:
	match character:
		DartData.Character.DAI:
			return _DAI
		DartData.Character.TERRY:
			return _TERRY
		DartData.Character.RAB:
			return _RAB
		DartData.Character.SIOBHAN:
			return _SIOBHAN
	return _DAI

const _DAI := [
	"Dai won the championship at 11:47pm on a Wednesday.",
	"",
	"By Thursday lunchtime he had eaten a kebab, signed a three-year deal with Bling Energy, and been photographed outside the venue with a trophy in one hand and a battered sausage in the other.",
	"",
	"By Thursday teatime, he was dead.",
	"",
	"Cardiac arrest.",
	"The paramedics said it was the most relaxed expression they'd ever seen on a man in that condition.",
	"The coroner noted he smelled of Jagermeister and achievement.",
	"He was 27.",
	"",
	"Jimi.",
	"Kurt.",
	"Amy.",
	"Dai.",
	"",
	"The funeral was standing room only.",
	"Inflatable dragons everywhere.",
	"The barman hosted the wake at The Farrier's Arms all afternoon and evening.",
	"",
	"A crowdfunding page was set up for a memorial.",
	"It raised 2.1 million in eleven days.",
	"Mostly from China.",
	"For reasons nobody at the time could explain.",
	"",
	"Alan handled the estate.",
	"There wasn't much.",
	"The darts. A dressing gown. A notebook with one line on the first page:",
	'"Idea for a business: DartCoin."',
	"Nothing else.",
	"",
	"A brass statue of Dai was unveiled outside Arrows Palace in 2029.",
	"It was enormous.",
	"Historians noted it caused a measurable hike in the price of brass across Europe.",
	"",
	"His daughter, Kayleigh-Renee, was just four years old when he died.",
	"She had never watched him play.",
	"",
	"At sixteen, she picked up a set of darts at a youth club in Merthyr Tydfil.",
	"She put three in the bullseye on her first visit.",
	"",
	"At age 27,",
	"she won the world championship.",
]

const _TERRY := [
	"Nobody told Terry that winning comes at a cost.",
	"Or rather, everyone told him.",
	"Alan. The barman. The leaflet on the back of the toilet door at The Farrier's Arms.",
	"He had processed all of it as background noise.",
	"",
	"So when his liver gave out, six weeks after the championship, it was a surprise only to him.",
	"He was sober for the first time in four years.",
	"It was not fun.",
	"",
	'"I can feel everything," he told Alan from the hospital bed. "Every single nerve. All of them. All going at once."',
	'"That\'s normal," said Alan.',
	'"It\'s horrible," said Terry.',
	'"Also normal," said Alan.',
	"",
	"Without the drunkenness to dull them, Terry's nerves were catastrophic.",
	"He attempted a comeback at a regional qualifier in Stoke.",
	"He threw three darts in quick succession.",
	"Into the wall. Then the ceiling. Then the floor.",
	"He retired from competitive play that afternoon and never picked up a dart again.",
	"",
	"He went back to university at 37.",
	"Sports Science. Then Psychology. Then Physics.",
	"",
	"He is currently employed at CERN.",
	"His colleagues know him as Terrence.",
	"None of them know about the darts. None of them know about the championship. None of them know about the liver.",
	"Just the occasional sight of the dartboard tattooed on the inside of his left wrist.",
	"",
	"In 2032, the PDC contacted him.",
	"They had discovered the connection.",
	"They wanted him for a promotional campaign:",
	"From the Oche to the Observable Universe.",
	"He declined.",
	"",
	"He did agree to one interview.",
	"A podcast. Forty-five minutes. No edits.",
	"He talked about the darts. The nerves. The drinking. The bling.",
	'"Do you miss it?" the host asked.',
	"He thought about it for longer than was comfortable.",
	"",
	'"Hell yeah."',
]

const _SIOBHAN := [
	"It lasted three months.",
	"That's how long Siobhan was famous.",
	"Three months of sponsors. Three months of photographs. Three months of being asked to stand next to things and say things about products she had never used or even heard of.",
	"Three months of being the top female in darts.",
	"In sport.",
	"",
	"Then the five-a-day scandal broke.",
	"",
	"Siobhan wanted the money.",
	"Just not the fame.",
	"",
	"Without any income, the winnings didn't last long.",
	"In search of a quieter life, she moved in with Big Kev.",
	"",
	"Big Kev had a caravan on a site outside Birmingham.",
	"It was not a large caravan.",
	"Big Kev was not a small man.",
	"The arrangement was, spatially, ambitious.",
	"They lived there for nineteen months.",
	"Both of them describe this period as one of the best of their lives.",
	"Which tells you something about everything that came before it.",
	"",
	"In February 2027, fuelled by ambition and questionable Wi-Fi, they launched DartCoin.",
	"The launch materials described it as:",
	'"A blockchain ecosystem underpinned by sporting values, elite performance, artificial intelligence, and world peace."',
	"Siobhan wrote this.",
	"She had not previously written anything longer than a text message.",
	"",
	"It worked, in the sense that things work before they don't.",
	"The price rose 400,000% in six weeks.",
	"Driven largely by a fan base in Japan.",
	"",
	"Siobhan cashed out in March.",
	"7,500,000 pounds.",
	"",
	"She is currently banned from four global financial exchanges.",
	"Under investigation by two more.",
	"",
	"She was last spotted boarding a flight to Rio de Janeiro.",
]

const _RAB := [
	"Rab never threw a dart again after the championship.",
	"",
	"He picked one up once.",
	"A pub in Osaka. 2026.",
	"He stood at the oche for four minutes without releasing it.",
	"Then put it down.",
	"Ordered a beer he didn't drink.",
	"Took a taxi back to the hotel in total silence.",
	"His translator asked if everything was alright.",
	"He said yes.",
	"She did not believe him.",
	"She was correct.",
	"",
	"He hasn't explained it since.",
	"Some things don't need explaining.",
	"Some things need to be left at the oche.",
	"",
	"He got into management by accident, the way most things happened to him.",
	"",
	"A kid at a regional qualifier in Coventry was throwing badly.",
	"Rab, watching from the bar, said something quiet to him between legs.",
	"What he said has never been repeated in public.",
	"",
	"The kid went back to the oche.",
	"170 checkout.",
	"Two 9-dart legs.",
	"Match won.",
	"",
	"Afterwards, a journalist found Rab at the bar with tears running down his face.",
	'"How did you know that?"',
	"Rab shrugged.",
	'"Same thing that was wrong with me."',
	"",
	"That kid was Danny Parr.",
	"Danny Parr has won the world championship three times.",
	"Rab managed him for all three.",
	"",
	"Then eight more world champions.",
	"Different player each year.",
	"It was Rab.",
	"It was all Rab.",
	"",
	"His phone rings constantly.",
	"Letters from four Premier League clubs. Two national rugby teams. An energy drink.",
	"",
	"But it's darts all the way for Rab.",
	"",
	"Always was.",
]
